export type SchemeType = "scholarship" | "loan" | "subsidy" | "grant";

export type Scheme = {
  id: string;
  name: string;
  ministry: string;
  launchedYear: number;
  status: string;
  schemeType: SchemeType;
  subType: string;
  tags: string[];
  source: string;
  amount: {
    value: number;
    min?: number;
    max?: number;
    frequency: string;
  };
  deadline: string | null;
  eligibility: {
    age?: { min: number; max: number };
    gender?: string[];
    caste?: string[];
    incomeMax?: number;
    education?: string[];
    occupation?: string[];
    states?: string[];
  };
  benefits: string[];
  website: string;
};

export const STATES = [
  "All India",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
];

export const EDUCATION_LEVELS = [
  "Below 10th",
  "10th Pass",
  "12th Pass",
  "Diploma",
  "Graduation",
  "Post Graduation",
  "PhD",
];

export const OCCUPATIONS = [
  "Student",
  "Employed",
  "Unemployed",
  "Farmer",
  "Entrepreneur",
  "Self-Employed",
  "Artisan",
  "Homemaker",
  "Healthcare Worker",
  "Teacher",
  "Government Employee",
];

export const SCHEME_TYPES: SchemeType[] = [
  "scholarship",
  "loan",
  "subsidy",
  "grant",
];

export const coreSchemes: Scheme[] = [
  {
    id: "nsp-sc-postmatric",
    name: "NSP Post Matric Scholarship for SC Students",
    ministry: "Ministry of Social Justice & Empowerment",
    launchedYear: 2012,
    status: "active",
    schemeType: "scholarship",
    subType: "post-matric",
    tags: ["sc", "student", "tuition", "need-based"],
    source: "scholarships.gov.in",
    amount: { value: 75000, min: 50000, max: 100000, frequency: "annual" },
    deadline: "2024-12-31",
    eligibility: {
      caste: ["SC"],
      incomeMax: 250000,
      education: ["12th Pass", "Diploma", "Graduation", "Post Graduation"],
      states: ["All India"],
    },
    benefits: ["Tuition fees", "Maintenance allowance", "Books & stationery"],
    website: "https://scholarships.gov.in",
  },
  {
    id: "nsp-st-postmatric",
    name: "NSP Post Matric Scholarship for ST Students",
    ministry: "Ministry of Social Justice & Empowerment",
    launchedYear: 2012,
    status: "active",
    schemeType: "scholarship",
    subType: "post-matric",
    tags: ["st", "student", "need-based"],
    source: "scholarships.gov.in",
    amount: { value: 75000, min: 50000, max: 100000, frequency: "annual" },
    deadline: "2024-12-31",
    eligibility: {
      caste: ["ST"],
      incomeMax: 250000,
      education: ["12th Pass", "Diploma", "Graduation", "Post Graduation"],
      states: ["All India"],
    },
    benefits: ["Tuition fees", "Maintenance allowance", "Exam fees"],
    website: "https://scholarships.gov.in",
  },
  {
    id: "nsp-obc-postmatric",
    name: "NSP Post Matric Scholarship for OBC Students",
    ministry: "Ministry of Social Justice & Empowerment",
    launchedYear: 2012,
    status: "active",
    schemeType: "scholarship",
    subType: "post-matric",
    tags: ["obc", "student", "need-based"],
    source: "scholarships.gov.in",
    amount: { value: 50000, min: 40000, max: 60000, frequency: "annual" },
    deadline: "2024-12-31",
    eligibility: {
      caste: ["OBC"],
      incomeMax: 300000,
      education: ["12th Pass", "Diploma", "Graduation", "Post Graduation"],
      states: ["All India"],
    },
    benefits: ["Tuition fees", "Maintenance allowance"],
    website: "https://scholarships.gov.in",
  },
  {
    id: "nsp-minority-prematric",
    name: "NSP Pre Matric Scholarship for Minority Communities",
    ministry: "Ministry of Minority Affairs",
    launchedYear: 2012,
    status: "active",
    schemeType: "scholarship",
    subType: "pre-matric",
    tags: ["minority", "student", "need-based"],
    source: "scholarships.gov.in",
    amount: { value: 30000, min: 25000, max: 35000, frequency: "annual" },
    deadline: "2024-09-30",
    eligibility: {
      incomeMax: 150000,
      education: ["Below 10th", "10th Pass"],
      states: ["All India"],
    },
    benefits: ["Tuition fees", "Book allowance"],
    website: "https://scholarships.gov.in",
  },
  {
    id: "aicte-pragati",
    name: "AICTE Pragati Scholarship for Girls",
    ministry: "Ministry of Education",
    launchedYear: 2014,
    status: "active",
    schemeType: "scholarship",
    subType: "gender-specific",
    tags: ["women", "technical", "engineering"],
    source: "aicte-india.org",
    amount: { value: 50000, min: 50000, max: 50000, frequency: "annual" },
    deadline: "2024-12-31",
    eligibility: {
      gender: ["female"],
      incomeMax: 800000,
      education: ["Diploma", "Graduation"],
      states: ["All India"],
    },
    benefits: ["Tuition support", "Incidental expenses"],
    website: "https://www.aicte-india.org",
  },
  {
    id: "begum-hazrat-mahal",
    name: "Begum Hazrat Mahal National Scholarship",
    ministry: "Maulana Azad Foundation",
    launchedYear: 2003,
    status: "active",
    schemeType: "scholarship",
    subType: "gender-specific",
    tags: ["minority", "women", "student"],
    source: "buddy4study.com",
    amount: { value: 11000, min: 10000, max: 12000, frequency: "annual" },
    deadline: "2024-09-30",
    eligibility: {
      gender: ["female"],
      incomeMax: 200000,
      education: ["10th Pass", "12th Pass"],
      states: ["All India"],
    },
    benefits: ["Financial assistance", "Academic support"],
    website: "https://www.buddy4study.com",
  },
  {
    id: "pm-scholarship",
    name: "Prime Minister's Scholarship Scheme",
    ministry: "PMO",
    launchedYear: 2006,
    status: "active",
    schemeType: "scholarship",
    subType: "defence",
    tags: ["defence", "student", "merit"],
    source: "mygov.in",
    amount: { value: 60000, min: 30000, max: 60000, frequency: "annual" },
    deadline: "2024-11-15",
    eligibility: {
      education: ["12th Pass", "Diploma", "Graduation"],
      states: ["All India"],
    },
    benefits: ["Tuition fees", "Monthly scholarship"],
    website: "https://www.desw.gov.in",
  },
  {
    id: "central-sector-scholarship",
    name: "Central Sector Scholarship Scheme",
    ministry: "Ministry of Education",
    launchedYear: 2008,
    status: "active",
    schemeType: "scholarship",
    subType: "merit-based",
    tags: ["merit", "higher-education", "student"],
    source: "scholarships.gov.in",
    amount: { value: 20000, min: 10000, max: 30000, frequency: "annual" },
    deadline: "2024-10-15",
    eligibility: {
      education: ["12th Pass", "Graduation"],
      states: ["All India"],
    },
    benefits: ["Merit scholarship", "Higher education support"],
    website: "https://scholarships.gov.in",
  },
  {
    id: "mudra-shishu",
    name: "Pradhan Mantri Mudra Yojana - Shishu",
    ministry: "Ministry of Finance",
    launchedYear: 2015,
    status: "active",
    schemeType: "loan",
    subType: "micro-business",
    tags: ["entrepreneur", "startup", "micro-loan"],
    source: "mudra.org.in",
    amount: { value: 250000, min: 50000, max: 500000, frequency: "one-time" },
    deadline: null,
    eligibility: {
      age: { min: 18, max: 65 },
      occupation: ["Entrepreneur", "Self-Employed"],
      states: ["All India"],
    },
    benefits: ["Collateral-free", "Low interest", "Flexible repayment"],
    website: "https://www.mudra.org.in",
  },
  {
    id: "mudra-kishor",
    name: "Pradhan Mantri Mudra Yojana - Kishor",
    ministry: "Ministry of Finance",
    launchedYear: 2015,
    status: "active",
    schemeType: "loan",
    subType: "small-business",
    tags: ["entrepreneur", "small-business", "loan"],
    source: "mudra.org.in",
    amount: { value: 2500000, min: 500001, max: 5000000, frequency: "one-time" },
    deadline: null,
    eligibility: {
      age: { min: 18, max: 65 },
      occupation: ["Entrepreneur", "Self-Employed"],
      states: ["All India"],
    },
    benefits: ["Business expansion", "Low interest"],
    website: "https://www.mudra.org.in",
  },
  {
    id: "standup-india",
    name: "Stand Up India Scheme",
    ministry: "Ministry of Finance",
    launchedYear: 2016,
    status: "active",
    schemeType: "loan",
    subType: "sc-st-women",
    tags: ["women", "sc", "st", "enterprise"],
    source: "standupmitra.in",
    amount: { value: 2500000, min: 1000000, max: 10000000, frequency: "one-time" },
    deadline: null,
    eligibility: {
      gender: ["female"],
      caste: ["SC", "ST"],
      occupation: ["Entrepreneur", "Self-Employed"],
      states: ["All India"],
    },
    benefits: ["Loan up to ₹1 Crore", "Handholding support"],
    website: "https://www.standupmitra.in",
  },
  {
    id: "startup-india-seed",
    name: "Startup India Seed Fund Scheme",
    ministry: "DPIIT",
    launchedYear: 2021,
    status: "active",
    schemeType: "loan",
    subType: "startup",
    tags: ["startup", "innovation", "tech"],
    source: "startupindia.gov.in",
    amount: { value: 5000000, min: 1000000, max: 10000000, frequency: "one-time" },
    deadline: null,
    eligibility: {
      occupation: ["Entrepreneur", "Self-Employed"],
      states: ["All India"],
    },
    benefits: ["Seed funding", "Mentorship"],
    website: "https://www.startupindia.gov.in",
  },
  {
    id: "pm-kisan",
    name: "PM-KISAN Samman Nidhi",
    ministry: "Ministry of Agriculture",
    launchedYear: 2019,
    status: "active",
    schemeType: "subsidy",
    subType: "income-support",
    tags: ["farmer", "agriculture", "income"],
    source: "pmkisan.gov.in",
    amount: { value: 6000, frequency: "annual" },
    deadline: null,
    eligibility: {
      occupation: ["Farmer"],
      states: ["All India"],
    },
    benefits: ["Direct income support"],
    website: "https://pmkisan.gov.in",
  },
  {
    id: "pm-ujjwala",
    name: "Pradhan Mantri Ujjwala Yojana",
    ministry: "Ministry of Petroleum & Natural Gas",
    launchedYear: 2016,
    status: "active",
    schemeType: "subsidy",
    subType: "energy",
    tags: ["women", "energy", "bpl"],
    source: "pmuy.gov.in",
    amount: { value: 1600, frequency: "one-time" },
    deadline: null,
    eligibility: {
      gender: ["female"],
      states: ["All India"],
    },
    benefits: ["Free LPG connection", "First refill subsidy"],
    website: "https://pmuy.gov.in",
  },
  {
    id: "pm-awas",
    name: "Pradhan Mantri Awas Yojana",
    ministry: "Ministry of Housing & Urban Affairs",
    launchedYear: 2015,
    status: "active",
    schemeType: "subsidy",
    subType: "housing",
    tags: ["housing", "urban", "rural"],
    source: "pmaymis.gov.in",
    amount: { value: 300000, min: 200000, max: 500000, frequency: "one-time" },
    deadline: null,
    eligibility: {
      incomeMax: 600000,
      states: ["All India"],
    },
    benefits: ["Interest subsidy", "Home construction support"],
    website: "https://pmaymis.gov.in",
  },
  {
    id: "pm-svanidhi",
    name: "PM Street Vendor's AtmaNirbhar Nidhi",
    ministry: "Ministry of Housing & Urban Affairs",
    launchedYear: 2020,
    status: "active",
    schemeType: "subsidy",
    subType: "livelihood",
    tags: ["street-vendor", "credit", "urban"],
    source: "pmsvanidhi.mohua.gov.in",
    amount: { value: 10000, min: 10000, max: 50000, frequency: "one-time" },
    deadline: null,
    eligibility: {
      occupation: ["Self-Employed", "Entrepreneur"],
      states: ["All India"],
    },
    benefits: ["Working capital loan", "Digital incentives"],
    website: "https://pmsvanidhi.mohua.gov.in",
  },
  {
    id: "pmkvy",
    name: "Pradhan Mantri Kaushal Vikas Yojana",
    ministry: "Ministry of Skill Development",
    launchedYear: 2015,
    status: "active",
    schemeType: "grant",
    subType: "skill-training",
    tags: ["youth", "skill", "training"],
    source: "pmkvyofficial.org",
    amount: { value: 80000, frequency: "one-time" },
    deadline: null,
    eligibility: {
      age: { min: 15, max: 45 },
      states: ["All India"],
    },
    benefits: ["Free skill training", "Certification"],
    website: "https://www.pmkvyofficial.org",
  },
  {
    id: "national-apprenticeship",
    name: "National Apprenticeship Training Scheme",
    ministry: "Ministry of Skill Development",
    launchedYear: 2014,
    status: "active",
    schemeType: "grant",
    subType: "apprenticeship",
    tags: ["youth", "stipend", "training"],
    source: "apprenticeshipindia.gov.in",
    amount: { value: 7000, min: 5000, max: 9000, frequency: "monthly" },
    deadline: null,
    eligibility: {
      age: { min: 16, max: 25 },
      education: ["Diploma", "Graduation"],
      states: ["All India"],
    },
    benefits: ["Monthly stipend", "Industry training"],
    website: "https://apprenticeshipindia.gov.in",
  },
];

const stateScholarshipTemplates = [
  {
    subType: "state-merit",
    tags: ["state", "merit", "student"],
    amount: { value: 40000, min: 30000, max: 60000, frequency: "annual" },
    eligibility: { education: ["12th Pass", "Graduation"] },
    ministrySuffix: "Department of Higher Education",
  },
  {
    subType: "state-need",
    tags: ["state", "need-based", "student"],
    amount: { value: 35000, min: 25000, max: 50000, frequency: "annual" },
    eligibility: { incomeMax: 300000, education: ["10th Pass", "12th Pass"] },
    ministrySuffix: "Social Welfare Department",
  },
  {
    subType: "state-girls",
    tags: ["state", "women", "student"],
    amount: { value: 45000, min: 35000, max: 65000, frequency: "annual" },
    eligibility: { gender: ["female"], education: ["12th Pass", "Graduation"] },
    ministrySuffix: "Women & Child Development Department",
  },
];

const stateLoanTemplates = [
  {
    subType: "msme-support",
    tags: ["msme", "enterprise"],
    amount: { value: 800000, min: 300000, max: 1500000, frequency: "one-time" },
  },
  {
    subType: "agri-credit",
    tags: ["agriculture", "farmer"],
    amount: { value: 250000, min: 100000, max: 500000, frequency: "one-time" },
    eligibility: { occupation: ["Farmer"] },
  },
  {
    subType: "education-loan",
    tags: ["education", "student"],
    amount: { value: 600000, min: 200000, max: 1500000, frequency: "one-time" },
    eligibility: { occupation: ["Student"] },
  },
];

const stateGrantTemplates = [
  {
    subType: "skill-support",
    tags: ["skill", "youth"],
    amount: { value: 25000, min: 15000, max: 40000, frequency: "one-time" },
  },
  {
    subType: "women-enterprise",
    tags: ["women", "enterprise"],
    amount: { value: 50000, min: 30000, max: 80000, frequency: "one-time" },
    eligibility: { gender: ["female"] },
  },
  {
    subType: "green-initiative",
    tags: ["energy", "sustainability"],
    amount: { value: 35000, min: 20000, max: 60000, frequency: "one-time" },
  },
];

const generatedStateSchemes: Scheme[] = STATES.filter(
  (state) => state !== "All India"
).flatMap((state) => {
  const scholarshipSchemes = stateScholarshipTemplates.map((template, index) => ({
    id: `${state.toLowerCase().replace(/\s+/g, "-")}-scholarship-${index + 1}`,
    name: `${state} Higher Education Scholarship ${index + 1}`,
    ministry: `${state} ${template.ministrySuffix}`,
    launchedYear: 2016 + index,
    status: "active",
    schemeType: "scholarship" as SchemeType,
    subType: template.subType,
    tags: [...template.tags, state.toLowerCase().replace(/\s+/g, "-")],
    source: "buddy4study.com",
    amount: template.amount,
    deadline: "2024-11-30",
    eligibility: {
      ...template.eligibility,
      states: [state],
    },
    benefits: ["Tuition assistance", "Maintenance allowance"],
    website: "https://www.buddy4study.com",
  }));

  const loanSchemes = stateLoanTemplates.map((template, index) => ({
    id: `${state.toLowerCase().replace(/\s+/g, "-")}-loan-${index + 1}`,
    name: `${state} MSME Growth Loan ${index + 1}`,
    ministry: `${state} Industries Department`,
    launchedYear: 2017 + index,
    status: "active",
    schemeType: "loan" as SchemeType,
    subType: template.subType,
    tags: [...template.tags, state.toLowerCase().replace(/\s+/g, "-")],
    source: "mygov.in",
    amount: template.amount,
    deadline: null,
    eligibility: {
      ...template.eligibility,
      states: [state],
      age: { min: 18, max: 65 },
    },
    benefits: ["Low interest", "Credit support", "Entrepreneurship mentoring"],
    website: "https://www.mygov.in",
  }));

  const grantSchemes = stateGrantTemplates.map((template, index) => ({
    id: `${state.toLowerCase().replace(/\s+/g, "-")}-grant-${index + 1}`,
    name: `${state} Skill & Enterprise Grant ${index + 1}`,
    ministry: `${state} Skill Development Mission`,
    launchedYear: 2018 + index,
    status: "active",
    schemeType: "grant" as SchemeType,
    subType: template.subType,
    tags: [...template.tags, state.toLowerCase().replace(/\s+/g, "-")],
    source: "state.gov.in",
    amount: template.amount,
    deadline: "2024-10-15",
    eligibility: {
      ...template.eligibility,
      states: [state],
      age: { min: 18, max: 40 },
    },
    benefits: ["Training support", "Toolkit grant", "Placement assistance"],
    website: "https://www.india.gov.in",
  }));

  return [...scholarshipSchemes, ...loanSchemes, ...grantSchemes];
});

export const sectorSubsidies: Scheme[] = [
  {
    id: "solar-rooftop",
    name: "National Rooftop Solar Subsidy",
    ministry: "Ministry of New & Renewable Energy",
    launchedYear: 2014,
    status: "active",
    schemeType: "subsidy",
    subType: "renewable-energy",
    tags: ["energy", "solar", "household"],
    source: "mnre.gov.in",
    amount: { value: 20000, min: 15000, max: 50000, frequency: "one-time" },
    deadline: null,
    eligibility: {
      states: ["All India"],
    },
    benefits: ["Subsidy on rooftop solar installation"],
    website: "https://www.mnre.gov.in",
  },
  {
    id: "pm-fme",
    name: "PM Formalisation of Micro Food Processing Enterprises",
    ministry: "Ministry of Food Processing Industries",
    launchedYear: 2020,
    status: "active",
    schemeType: "subsidy",
    subType: "food-processing",
    tags: ["msme", "food", "entrepreneur"],
    source: "mofpi.gov.in",
    amount: { value: 100000, min: 50000, max: 300000, frequency: "one-time" },
    deadline: null,
    eligibility: {
      occupation: ["Entrepreneur", "Self-Employed"],
      states: ["All India"],
    },
    benefits: ["Credit-linked subsidy", "Capacity building"],
    website: "https://mofpi.gov.in",
  },
  {
    id: "pmfby",
    name: "Pradhan Mantri Fasal Bima Yojana",
    ministry: "Ministry of Agriculture",
    launchedYear: 2016,
    status: "active",
    schemeType: "subsidy",
    subType: "crop-insurance",
    tags: ["farmer", "insurance", "agriculture"],
    source: "pmfby.gov.in",
    amount: { value: 25000, min: 10000, max: 50000, frequency: "annual" },
    deadline: "2024-07-31",
    eligibility: {
      occupation: ["Farmer"],
      states: ["All India"],
    },
    benefits: ["Premium subsidy", "Crop loss coverage"],
    website: "https://pmfby.gov.in",
  },
  {
    id: "pm-vishwakarma",
    name: "PM Vishwakarma Yojana",
    ministry: "Ministry of MSME",
    launchedYear: 2023,
    status: "active",
    schemeType: "grant",
    subType: "artisan-support",
    tags: ["artisan", "toolkit", "skill"],
    source: "msme.gov.in",
    amount: { value: 300000, min: 100000, max: 500000, frequency: "one-time" },
    deadline: null,
    eligibility: {
      occupation: ["Artisan", "Self-Employed"],
      states: ["All India"],
    },
    benefits: ["Toolkit grant", "Skill training", "Market linkage"],
    website: "https://msme.gov.in",
  },
  {
    id: "nrega",
    name: "Mahatma Gandhi National Rural Employment Guarantee Scheme",
    ministry: "Ministry of Rural Development",
    launchedYear: 2006,
    status: "active",
    schemeType: "grant",
    subType: "employment",
    tags: ["rural", "employment", "livelihood"],
    source: "nrega.nic.in",
    amount: { value: 28000, min: 20000, max: 40000, frequency: "annual" },
    deadline: null,
    eligibility: {
      occupation: ["Unemployed", "Self-Employed", "Farmer"],
      states: ["All India"],
    },
    benefits: ["Guaranteed wage employment", "Skill development"],
    website: "https://nrega.nic.in",
  },
];

export const allSchemes: Scheme[] = [
  ...coreSchemes,
  ...sectorSubsidies,
  ...generatedStateSchemes,
];
